services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/
    depends_on:
      - database
    environment:
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 0
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_INTL: 1
      STARTUP_COMMAND_1: composer install

