version: '2' #rancher 1 must have here

services:
    php:
        image: ghcr.io/steinbauer/synthetic-editorial:latest
        labels:
            io.rancher.container.pull_image: always
            io.rancher.scheduler.affinity:host_label_ne: machine=ps2
            traefik.synthetic_polyweb_cz.frontend.rule: Host:synthetic.polyweb.cz
            traefik.synthetic_polyweb_cz.frontend.redirect.entryPoint: https
            traefik.enable: 'true'
            traefik.protocol: http
            traefik.port: 80
        environment:
            NETTE_DEBUG: 0
            PHP_EXTENSION_XDEBUG: 0
            PHP_EXTENSION_PGSQL: 1
            PHP_EXTENSION_PDO_PGSQL: 1
            PHP_EXTENSION_MYSQLI: 0
            PHP_EXTENSION_GD: 1
            PHP_EXTENSION_INTL: 1
            STARTUP_COMMAND_1: composer install
            STARTUP_COMMAND_2: php bin/console migrations:migrate --no-interaction --allow-no-migration
    database:
        image: dockette/postgres:10
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - /var/primary/nfs_share/synthetic-editorial:/var/lib/postgresql/data
