# .github/workflows/deploy.yml
name: "CI/CD: PHPStan + Docker Build + Rancher Deploy"

on:
    push:
        branches: [main]

jobs:
    phpstan:
        name: Phpstan
        uses: contributte/.github/.github/workflows/phpstan.yml@v1
        with:
            make: "init github-phpstan"

    docker:
        name: Build & Push Docker Image
        runs-on: ubuntu-latest
        needs: phpstan

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u steinbauer --password-stdin

            - name: Build Docker image
              run: docker build -t ghcr.io/steinbauer/synthetic-editorial:latest -f .docker/php/Dockerfile .

            - name: Push Docker image
              run: docker push ghcr.io/steinbauer/synthetic-editorial:latest

    deploy:
        name: Deploy to Rancher
        runs-on: ubuntu-latest
        needs: docker

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v3

            -   name: Create .env file from secrets
                run: |
                    echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
                    echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
                    echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

            -   name: Install Rancher CLI
                run: |
                    curl -sL https://github.com/rancher/cli/releases/download/v0.6.4/rancher-linux-amd64-v0.6.4.tar.gz | tar xz
                    sudo mv rancher-v0.6.4/rancher /usr/local/bin/rancher

            -   name: Deploy database (soft upgrade only)
                run: |
                    rancher --url "${{ secrets.RANCHER_URL }}" \
                            --access-key "${{ secrets.RANCHER_ACCESS_KEY }}" \
                            --secret-key "${{ secrets.RANCHER_SECRET_KEY }}" \
                            --env "${{ secrets.RANCHER_ENVIRONMENT }}" \
                            up -d --stack "${{ secrets.RANCHER_STACK_NAME }}" \
                            --file docker-compose.prod.yml \
                            --env-file .env \
                            --rancher-file rancher-compose.yml \
                            --upgrade --confirm-upgrade \
                            database

            -   name: Deploy PHP (force upgrade)
                run: |
                    rancher --url "${{ secrets.RANCHER_URL }}" \
                            --access-key "${{ secrets.RANCHER_ACCESS_KEY }}" \
                            --secret-key "${{ secrets.RANCHER_SECRET_KEY }}" \
                            --env "${{ secrets.RANCHER_ENVIRONMENT }}" \
                            up -d --stack "${{ secrets.RANCHER_STACK_NAME }}" \
                            --file docker-compose.prod.yml \
                            --env-file .env \
                            --rancher-file rancher-compose.yml \
                            --force-upgrade --confirm-upgrade \
                            php

