deploy:
    name: Deploy to Rancher
    runs-on: ubuntu-latest
    needs: docker  # after build

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Install Rancher CLI
          run: |
              curl -sL https://github.com/rancher/cli/releases/download/v0.6.4/rancher-linux-amd64-v0.6.4.tar.gz | tar xz
              sudo mv rancher-v0.6.4/rancher /usr/local/bin/rancher

        - name: Deploy app to Rancher
          run: |
              rancher --url "${{ secrets.RANCHER_URL }}" \
                      --access-key "${{ secrets.RANCHER_ACCESS_KEY }}" \
                      --secret-key "${{ secrets.RANCHER_SECRET_KEY }}" \
                      up -d --stack "synthetic-editorial" \
                      --file docker-compose.prod.yml \
                      --rancher-file rancher-compose.yml \
                      --pull --upgrade --confirm-upgrade
