name: "CI/CD: PHPStan + Docker Build"

on:
    push:
        branches: [main]

jobs:
    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: composer

            - name: Install dependencies
              run: composer install

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=512M

    docker:
        name: Build & Push Docker Image
        runs-on: ubuntu-latest
        needs: phpstan  # Wait for PHPStan to finish before starting this job

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build Docker image
              run: docker build -t ghcr.io/${{ github.repository_owner }}/synthetic-editorial:latest -f .docker/php/Dockerfile .

            - name: Push Docker image
              run: docker push ghcr.io/${{ github.repository_owner }}/synthetic-editorial:latest
