name: "CI/CD: PHPStan + Docker Build"

on:
    push:
        branches: [main]

jobs:
    phpstan:
        name: "Phpstan"

        on:
            pull_request:

            push:
                branches: ["*"]

            schedule:
                - cron: "0 8 * * 1"

        jobs:
            phpstan:
                name: "Phpstan"
                uses: contributte/.github/.github/workflows/phpstan.yml@v1
                with:
                    make: "init github-phpstan"

    docker:
        name: Build & Push Docker Image
        runs-on: ubuntu-latest
        needs: phpstan  # Wait for PHPStan to finish before starting this job

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build Docker image
              run: docker build -t ghcr.io/${{ github.repository_owner }}/synthetic-editorial:latest -f .docker/php/Dockerfile .

            - name: Push Docker image
              run: docker push ghcr.io/${{ github.repository_owner }}/synthetic-editorial:latest
